version: "3.8"
services:
  expo:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${API_PORT}:8000"
    env_file:
      - .env
    restart: "unless-stopped"
    deploy:
      resources:
        limits:
          memory: 2G